---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: mybitnami
  namespace: flux-system
spec:
  type: "oci"
  interval: 1m0s
  url: oci://registry-1.docker.io/bitnamicharts/
