---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    usePassword: false
    cluster:
      enabled: false
  interval: 5m0s
  releaseName: redis
  storageNamespace: default
  targetNamespace: default

