---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 1m
  releaaseName: redis
  chartRef:
    kind: OCIRepository
    name: myocirepository
  values:
    usePassword: false
    cluster:
      enabled: false
  storageNamespace: default
  targetNamespace: default
