---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  chartRef:
    kind: OCIRepository
    name: mybitnami
  values:
    usePassword: false
    cluster:
      enabled: false
  interval: 5m0s
  releaseName: redis
  storageNamespace: default
  targetNamespace: default
