---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis
  namespace: flux-system
spec:
  interval: 1m
  releaseName: redis
  chartRef:
    kind: OCIRepository
    name: myocibitnami
  values:
    usePassword: false
    cluster:
      enabled: false
    image:
      repository: bitnamilegacy/redis
      tag: "8.2.1-debian-12-r0"
  storageNamespace: default
  targetNamespace: default
